### ISSUE TITLE
Model when use Carbon, auto generate docblock not pass by phpstan.

### ISSUE THREAD

**Issue by bolechen** [barryvdh/laravel-ide-helper#1004]
this is my User Model diff after run `php artisan ide-helper:models -WR`

<img width="994" alt="image" src="https://user-images.githubusercontent.com/195015/89158878-49a19a80-d5a1-11ea-8f63-2e8bfd08d709.png">

it will remove `\Carbon\Carbon` in docblock, would lead to result by phpstan: (https://github.com/nunomaduro/larastan)

```
 ------ -----------------------------------------------------------------------
  Line   User.php
 ------ -----------------------------------------------------------------------
  385    Property App\User::$vip_end (Illuminate\Support\Carbon|null) does not
         accept Carbon\Carbon.
  388    Property App\User::$vip_end (Illuminate\Support\Carbon|null) does not
         accept Carbon\Carbon.
  394    Property App\User::$vip_end (Illuminate\Support\Carbon|null) does not
         accept Carbon\Carbon.
 ------ -----------------------------------------------------------------------
```

Is there something I'm doing wrong? Please advise, thank you very much!

**Comment by bolechen** [comment]
my php code sample below

```php
                $this->vip_end = $this->vip_end->addDays($vip_days);
```

**Comment by mfn** [comment]
I wondered if my PR https://github.com/barryvdh/laravel-ide-helper/pull/859 is responsible but I'm not sure because it looks like when I made the PR, there was already no `Carbon\Carbon` referenced in the code I changed 🤔

**Comment by mfn** [comment]
How did you end up with `null|\Carbon\Carbon|Illuminate\Support\Carbon` in the first place (from your screenshot)?

I've never seen it generated that way from ide-helper?

Even the `null|\Illuminate\Support\Carbon` is strange, because `null` is always appended…

Or did you simply have another tool reformatting that before you pasted it? 🤔

**Comment by mfn** [comment]
> `null|\Carbon\Carbon|Illuminate\Support\Carbon`

What I mean is: ide-helper never generated the union `\Carbon\Carbon|Illuminate\Support\Carbon`.

- My PR added support for runtime override of the Facade => https://github.com/barryvdh/laravel-ide-helper/pull/859/files#diff-9c76e55ce4ef570404e58c82d642c1e5R299
- before that it was https://github.com/barryvdh/laravel-ide-helper/blame/027e58fd568a46b339452b78557e6f3c56744e48/src/Console/ModelsCommand.php#L287
- before that it was https://github.com/barryvdh/laravel-ide-helper/blame/28f0ac3781c451793ff1c50c8980be1a377936c0/src/Console/ModelsCommand.php#L280

So it never was a union

**Comment by mfn** [comment]
Interesting idea.

However I'm not seeing myself pursuing this, as if will cause additional confusion when people see the result is `\Illuminate\Support\Carbon`.

Was my hunch right that?
> So it's either "IDE" or "static analyzers" at the moment?

**Comment by kylekatarnls** [comment]
Actually I would like to PHPDoc the Carbon method with some `@return static` but when set as a `@method` annotation, the `static` keyword is detected as a static-method marker instead of the return type. So I don't know how I could achieve the right typing and properly detected by the IDE too.

**Comment by kylekatarnls** [comment]
A other possible fix is to copy-paste the `\Carbon\Carbon` PHPDoc over the `\Illuminate\Support\Carbon` PHPDoc. This would not be a good thing for the Laravel repository to hard-code this duplicate right in their source, so it should rather be some script to run to override it.

Maybe I can propose a fix for `ide-helper:generate` to generate the needed extra PHPDoc.

**Comment by kylekatarnls** [comment]
I also could change `Carbon` with `$this` in the PHPDoc which make the typing of sub-classes correct but this would only be correct for `Carbon\Carbon`, not  for `Carbon\CarbonImmutable` for which the same methods return new instances.

**Comment by mfn** [comment]
> but when set as a @method annotation, the static keyword is detected as a static-method marker instead of the return type. So I don't know how I could achieve the right typing and properly detected by the IDE too.

This may related to https://youtrack.jetbrains.com/issue/WI-54071 …

> I also could change `Carbon` with `$this` in the PHPDoc

You in fact did, didn't you? => https://github.com/briannesbitt/Carbon/commit/0a41ea7f7fedacf307b7a339800e10356a042918

Because I was about to test this "in code" in an up2date project and I couldn't reproduce it 😅 when I realized `vendor/nesbot/carbon/src/Carbon/Carbon.php` had `$this` everywhere already.

> but this would only be correct for `Carbon\Carbon`, not for `Carbon\CarbonImmutable`

I guess it's fine, because:
- `\Illuminate\Support\Carbon` does not extend Immutable
- when using your Laravel customization `Date::use(CarbonImmutable::class)`, ide-helper already detects and does generate the `CarbonImmutable` typehint which works correctly

----
The way I see it, with the release nestbot/carbon 2.39.0 everything is solved and we don't need https://github.com/barryvdh/laravel-ide-helper/pull/1014 ?

**Comment by kylekatarnls** [comment]
Yes it should be 👌

**Comment by mfn** [comment]
Solved it is then 😄

**Comment by denniskoster** [comment]
I am sorry, but I fail to see how this has been solved. I am still experiencing this exact issue, where the the generated docblocks state `Illuminate\Support\Carbon|null` and not `Carbon\Carbon`. I am on `nesbot/carbon 2.40.1` and `barryvdh/laravel-ide-helper 2.8.1`.

**Comment by Sergiobop** [comment]
This is not solved @kylekatarnls @mfn. You can check https://github.com/nunomaduro/larastan/issues/1067. The packages are not compatible right now
